-- MySQL Script generated by MySQL Workbench
-- 04/06/14 19:00:52
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pracownik_typ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pracownik_typ` (
  `idpracownik_typ` INT NOT NULL,
  `pracownik_typ_nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idpracownik_typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pracownik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pracownik` (
  `idpracownik` INT NOT NULL,
  `pracownik_imie` VARCHAR(45) NULL,
  `pracownik_nazwisko` VARCHAR(45) NULL,
  `pracownik_login` VARCHAR(45) NULL,
  `pracownik_haslo` VARCHAR(45) NULL,
  `pracownik_email` VARCHAR(45) NULL,
  `pracownik_adres` VARCHAR(45) NULL,
  `pracownik_data` DATE NULL,
  `pracownik_typ_idpracownik_typ` INT NOT NULL,
  PRIMARY KEY (`idpracownik`, `pracownik_typ_idpracownik_typ`),
  INDEX `fk_pracownik_pracownik_typ1_idx` (`pracownik_typ_idpracownik_typ` ASC),
  CONSTRAINT `fk_pracownik_pracownik_typ1`
    FOREIGN KEY (`pracownik_typ_idpracownik_typ`)
    REFERENCES `mydb`.`pracownik_typ` (`idpracownik_typ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`czytelnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`czytelnik` (
  `idczytelnik` INT NOT NULL,
  `czytelnik_imie` VARCHAR(45) NULL,
  `czytelnik_nazwisko` VARCHAR(45) NULL,
  `czytelnik_dlug` FLOAT NULL,
  `czytelnik_wypozyczone` INT NULL,
  `czytelnik_aktywny` TINYINT(1) NULL,
  `czytelnik_rezerwacja` INT NULL,
  PRIMARY KEY (`idczytelnik`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksiazka_okres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksiazka_okres` (
  `idksiazka_okres` INT NOT NULL,
  `ksiazka_okres_nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idksiazka_okres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksiazka_typ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksiazka_typ` (
  `idksiazka_typ` INT NOT NULL,
  `ksiazk_typ_nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idksiazka_typ`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wydawca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`wydawca` (
  `idwydawca` INT NOT NULL,
  `wydawca_nazwa` VARCHAR(45) NULL,
  `wydawca_adres` VARCHAR(45) NULL,
  `wydawca_status` TINYINT(1) NULL,
  PRIMARY KEY (`idwydawca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rok`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rok` (
  `idrok` INT NOT NULL,
  `rok_nr` YEAR NULL,
  PRIMARY KEY (`idrok`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`narodowosc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`narodowosc` (
  `idnarodowosc` INT NOT NULL,
  `narodowosc_nazwa` VARCHAR(45) NULL,
  PRIMARY KEY (`idnarodowosc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`autor` (
  `idautor` INT NOT NULL,
  `autor_imie` VARCHAR(45) NULL,
  `autor_nazwisko` VARCHAR(45) NULL,
  `narodowosc_idnarodowosc` INT NOT NULL,
  PRIMARY KEY (`idautor`, `narodowosc_idnarodowosc`),
  INDEX `fk_autor_narodowosc_idx` (`narodowosc_idnarodowosc` ASC),
  CONSTRAINT `fk_autor_narodowosc`
    FOREIGN KEY (`narodowosc_idnarodowosc`)
    REFERENCES `mydb`.`narodowosc` (`idnarodowosc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ksiazka`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ksiazka` (
  `idksiazka` INT NOT NULL,
  `ksiazka_nazwa` VARCHAR(45) NULL,
  `ksiazka_rezerwacja` TINYINT(1) NULL,
  `ksiazka_wypozyczona` TINYINT(1) NULL,
  `ksiazka_okres_idksiazka_okres` INT NOT NULL,
  `ksiazka_typ_idksiazka_typ` INT NOT NULL,
  `wydawca_idwydawca` INT NOT NULL,
  `rok_idrok` INT NOT NULL,
  `czytelnik_idczytelnik` INT NOT NULL,
  `autor_idautor` INT NOT NULL,
  `autor_narodowosc_idnarodowosc` INT NOT NULL,
  PRIMARY KEY (`idksiazka`, `ksiazka_okres_idksiazka_okres`, `ksiazka_typ_idksiazka_typ`, `wydawca_idwydawca`, `rok_idrok`, `czytelnik_idczytelnik`, `autor_idautor`, `autor_narodowosc_idnarodowosc`),
  INDEX `fk_ksiazka_ksiazka_okres1_idx` (`ksiazka_okres_idksiazka_okres` ASC),
  INDEX `fk_ksiazka_ksiazka_typ1_idx` (`ksiazka_typ_idksiazka_typ` ASC),
  INDEX `fk_ksiazka_wydawca1_idx` (`wydawca_idwydawca` ASC),
  INDEX `fk_ksiazka_rok1_idx` (`rok_idrok` ASC),
  INDEX `fk_ksiazka_czytelnik1_idx` (`czytelnik_idczytelnik` ASC),
  INDEX `fk_ksiazka_autor1_idx` (`autor_idautor` ASC, `autor_narodowosc_idnarodowosc` ASC),
  CONSTRAINT `fk_ksiazka_ksiazka_okres1`
    FOREIGN KEY (`ksiazka_okres_idksiazka_okres`)
    REFERENCES `mydb`.`ksiazka_okres` (`idksiazka_okres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksiazka_ksiazka_typ1`
    FOREIGN KEY (`ksiazka_typ_idksiazka_typ`)
    REFERENCES `mydb`.`ksiazka_typ` (`idksiazka_typ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksiazka_wydawca1`
    FOREIGN KEY (`wydawca_idwydawca`)
    REFERENCES `mydb`.`wydawca` (`idwydawca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksiazka_rok1`
    FOREIGN KEY (`rok_idrok`)
    REFERENCES `mydb`.`rok` (`idrok`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksiazka_czytelnik1`
    FOREIGN KEY (`czytelnik_idczytelnik`)
    REFERENCES `mydb`.`czytelnik` (`idczytelnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ksiazka_autor1`
    FOREIGN KEY (`autor_idautor` , `autor_narodowosc_idnarodowosc`)
    REFERENCES `mydb`.`autor` (`idautor` , `narodowosc_idnarodowosc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
